### ISSUE TITLE
P2pool for GLT

### ISSUE THREAD

**Issue by p3yot3** [globaltoken/globaltoken#9]
Are there any plans to add a p2pool repo for GLT? I'd like to mine it.

Nice work btw.

**Comment by globaltoken** [comment]
Hey mate,

What exactly is p2pool ?
Do you have a base directory that I could fork, then I could review that.

Thanks anyways, we used new clean Source Code now :)

Cheers,

First Dev.

**Comment by p3yot3** [comment]
Here is the most common p2pool repo for altcoins:

https://github.com/Rav3nPL/p2pool-rav

Although if GLT uses segwit this will not work.

**Comment by globaltoken** [comment]
So should I commit GLT now there or not?

**Comment by p3yot3** [comment]
I just noticed GLT uses segwit - so is incompatible with p2pool.

**Comment by globaltoken** [comment]
I could create a Pull Request to add SegWit Support if you want.

**Comment by p3yot3** [comment]
In that case, you should probably do it on the official p2pool repo:

https://github.com/p2pool/p2pool

**Comment by globaltoken** [comment]
We will consider it in future Releases.
If you know in the future, that p2pool allows SegWit blocks, pls let me know here or open a new issue / pull request.

Thanks for contributing!

Kind regards,

Dev Team
